all:
  vars:
    ansible_user: ansible
    ansible_become: true
    ansible_become_method: sudo
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null'
  children:
    database_servers:
      hosts:
        cdc-db-source:
          ansible_host: 192.168.29.211
        cdc-db-target:
          ansible_host: 192.168.29.214
    kafka_servers:
      hosts:
        cdc-kafka:
          ansible_host: 192.168.29.212
    connect_servers:
      hosts:
        cdc-connect:
          ansible_host: 192.168.29.213
    postgres_source:
      hosts:
        cdc-db-source:
          ansible_host: 192.168.29.211
    postgres_target:
      hosts:
        cdc-db-target:
          ansible_host: 192.168.29.214
    kafka_cluster:
      hosts:
        cdc-kafka:
          ansible_host: 192.168.29.212
    kafka_connect_cluster:
      hosts:
        cdc-connect:
          ansible_host: 192.168.29.213
